name: mayr_result
description: >
  A lightweight functional-style Result type for Dart that represents success or failure outcomes.

  Simplifies error handling by replacing exceptions with safe, expressive result objects.
version: 1.0.0
homepage: https://github.com/YoungMayor/mayr_dart_result
repository: https://github.com/YoungMayor/mayr_dart_result
issue_tracker: https://github.com/YoungMayor/mayr_dart_result/issues
documentation: https://github.com/YoungMayor/mayr_dart_result/wiki
LICENSE: MIT

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# dependencies:
# path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

topics:
  - result
  - utilities
  - dart
  - productivity
  - toolkit
